---
title: "RStudio Server Pro Training Environment for Intro to R Workshop"
output: html_notebook
---

## Plan

- Add valid key to `.key` ✓
- Add a Dockerfile which:
    - inherits from `rstudio/rstudio-server-pro:latest` (https://hub.docker.com/r/rstudio/rstudio-server-pro)
    - installs system packages: `libxml2-dev` and `vim` (after `apt-get update`)
    - installs R packages: `tidyverse`, `rmarkdown`, `shiny`, `flexdashboard`, `devtools`
    - clones `https://github.com/skadauke/intro-to-r-for-clinicians-rmed2020`
    - moves files from dir into user directory, only keeping files necessary for the workshop
    - creates a text file with logins and passwords of a pre-specified length (argument to docker command)
    - creates users from a text file with logins and passwords (rmed001 through rmed009 are instructors)
    - deletes temp user
- Important: if you build a docker image from the above, updates to the git repo will not be incorporated unless it's build with `--no-cache` option set
- Launcher / Kubernetes needs named license (I think I have a server based license) - will need to figure out if I need this. To deactive launcher, need to pass `-e RSP_LAUNCHER="false"`
    - Need the following inside `server-pro/conf` dir which will be mounted to `/etc/rstudio`:
        - `launcher.conf`
        - `rserver.conf`
        - `jupyter.conf`
- In order to have persistent data, will need to mount `/home` to a persisent volume on the host machine or an NFS volume

## Start a single server locally on a Docker container

- Access server on http://localhost:8787

```{bash, eval = FALSE}
# Load key from .key - excluded from git repo
source .key

export RSP_LICENSE=$MY_RSP_LICENSE
export RSP_TESTUSER="rmed000"
export RSP_TESTUSER_PASSWD="r@med-2020"

# Run without persistent data and using an external configuration
docker run --privileged -it \
    -p 8787:8787 -p 5559:5559 \
    -v "$PWD/server-pro/conf/":"/etc/rstudio" \
    -e RSP_LICENSE=$RSP_LICENSE \
    -e RSP_TESTUSER=$RSP_TESTUSER \
    -e RSP_TESTUSER_PASSWD=$RSP_TESTUSER_PASSWD \
    -e RSP_LAUNCHER="false" \
    rstudio/rstudio-server-pro:latest
```

## Generate a list of usernames and passwords

```{r}
library(glue)
library(tidyverse)

n_users <- 200

secret_seed <- as.integer(Sys.getenv("secret_seed")) # from .Renviron which is not shared on GitHub

set.seed(secret_seed)
users <- tibble(
    username = glue("rmed{1:n_users %>% str_pad(3, '0', side = 'left')}"),
    password = runif(n_users, min = 0, max = 999999) %>% as.integer %>% str_pad(6, '0', side = "left")
)

users %>%
    write_tsv("users.txt", col_names = FALSE)
```

## Generate user accounts from a list of usernames and passwords

```{bash, eval = FALSE}
#!/bin/bash
USER_FILE="users.txt"
TEMPLATE_USER_DIR=/home/rmed000
DEBUG=false

if [[ ! -d $TEMPLATE_USER_DIR ]]; then
    printf 'Error: Template dir %s does not exist.\n' $TEMPLATE_USER_DIR
    exit 1
fi

while IFS=$'\t' read -r USERNAME PASSWORD || [[ -n $USERNAME ]]
do
    # Deal with new line at the end of the file
    if [[ -z "$USERNAME" ]]; then
        continue
    fi

    # Skip existing users
    USER_EXISTS=$(id -u $USERNAME > /dev/null 2>&1; echo $?)
    if [[ "$USER_EXISTS" -eq "0" ]]; then
        printf '# User %s exists, skipping\n' $USERNAME
        continue
    fi

    printf '# Create user %s with password %s\n' $USERNAME $PASSWORD

    # Start useradd command
    CMD="useradd --shell /bin/bash -g users -p \$(openssl passwd -1 $PASSWORD)"

    # Add home dir, unless existing
    HOME_DIR="/home/$USERNAME"
    if [ ! -d "$HOME_DIR" ]; then
        CMD=`printf '%s --create-home' "$CMD"`
    fi

    # Sudo users rmed001 through rmed009 (to be used by instructors)
    if [[ $USERNAME =~ ^rmed00[1-9] ]]; then
        CMD=`printf '%s %s' "$CMD" "-G sudo"`
    fi

    CMD=`printf '%s %s' "$CMD" "$USERNAME"`

    if $DEBUG; then
        printf 'RUN: %s\n' "$CMD"
    fi

    eval $CMD

done < $USER_FILE
```

## Build and run docker image

```{bash, eval = FALSE}
docker build --no-cache -t rsp-rmed2020 . 


docker run -it rsp-rmed2020
```
